# Generated by Django 2.2.1 on 2019-05-23 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='data_addeded',
            new_name='data_added',
        ),
    ]
